### ISSUE TITLE
How to write CUDA?

### ISSUE THREAD

**Issue by pogevip** [clangd/vscode-clangd#125]
![image](https://user-images.githubusercontent.com/27748841/102954814-58b4c500-450f-11eb-9001-28075ed8ca1f.png)

**Comment by cloudhan** [comment]
You should add a `.clangd` file

```yaml
CompileFlags:
  Add:
    - -std=c++11
    - --cuda-path=/usr/local/cuda
    - --cuda-gpu-arch=sm_61
    - -L/usr/local/cuda/lib64
    - -I/usr/local/cuda/include
```

clangd seems to not working on windows though...
