### ISSUE TITLE
[Feature request]Ability to switch between warning, hint & info VS Code linting channels for Clang-tidy checks and Clang -w warnings

### ISSUE THREAD

**Issue by ItsCubeTime** [clangd/vscode-clangd#179]
So VS Code has several linting channels for language servers, errors, warnings, info & hints. 

However at the time being it seems its not possible to display feedback from clangd in any other channel than the warning (and errors) channel(s), many of which would probably better fit in something like a hint or info channel (see screenshot).

![image](https://user-images.githubusercontent.com/20190653/115418153-8da10200-a1f9-11eb-90e2-e0f9f8f95e31.png)

Thanks for reading <3

**Comment by njames93** [comment]
I feel this is something that could be controlled via Config in a similar way to `Diagnostics->Suppress`
```yaml
Diagnostics:
  AGoodNameForAnOptionToLowerDiagnosticsToHintLevel:
    - Wunused-parameter # clang warning flags
    - performance-noexcept-move-constructor # clang-tidy warnings 
```
