### ISSUE TITLE
Help request: clang-tidy does not work

### ISSUE THREAD

**Issue by deadb0d4** [clangd/vscode-clangd#256]
I use two folder workspace in vscode with the following settings:

```json
    "settings": {
        "C_Cpp.autocomplete": "Disabled",
        "C_Cpp.errorSquiggles": "Disabled",
        "C_Cpp.intelliSenseEngine": "Disabled",
        "clangd.arguments": [
            "--log=verbose",
            "--pretty",
            "--background-index",
            "--compile-commands-dir=/tmp/build-dir/build",
            "--clang-tidy",
            "-j=2"
        ],
        "clangd.path": "/usr/local/bin/clangd",
        "editor.tabSize": 2,
        "terminal.integrated.tabs.enabled": false
    }
```

[dot]clang-tidy file is located only in one of the folders. My operating system is

```
lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.6 LTS
Release:        18.04
Codename:       bionic
```

I downloaded pre-built clangd binary from [here](https://github.com/clangd/clangd/releases), this is the version:
```
clangd --version
clangd version 13.0.0 (https://github.com/llvm/llvm-project d7b669b3a30345cfcdb2fde2af6f48aa4b94845d)
Features: linux+grpc
Platform: x86_64-unknown-linux-gnu
```

Could you please help me out why clang-tidy seem to be not used completely? I don't know how I can diagnose this on my own...

**Comment by kadircet** [comment]
you've just provided some parts of your configuration without really explaining what are the symptoms of clang-tidy "not working".

please tell us more about, what you did, what you expected and what happened in reality and the relevant environment while you were performing these e.g. clangd configuration, directory layouts (especially locations of .clang-tidy and .clangd files), contents of those configuration files as well.

**Comment by deadb0d4** [comment]
As a simple test, I wrote the following
```c++
std::string w1{"..."};
auto w2 = std::move(w1);
std::cout << w1[0] << std::endl;
```
which causes a warning in my home laptop, but causes nothing on the machine in the subject.

---

I've written all the settings involved in the clangd vscode configuration. Apart from it, it is straight out of the box from the github pre-built packages.

---

Directory layout of the workspace involved is as follows:
```
/tmp/build-dir/build/*

$HOME/source_code_folder/*
```
where in the latter, `.clang-tidy` file is stored with the following content:
```
Checks: '-*,bugprone-*,cert-dcl21-cpp,cert-dcl50-cpp,cert-env33-c,cert-err34-c,cert-err52-cpp,cert-err60-cpp,cert-flp30-c,cert-msc50-cpp,cert-msc51-cpp,cppcoreguidelines-*,-cppcoreguidelines-macro-usage,-cppcoreguidelines-pro-type-reinterpret-cast,-cppcoreguidelines-pro-type-union-access,-cppcoreguidelines-pro-bounds-pointer-arithmetic,-cppcoreguidelines-pro-type-vararg,google-build-using-namespace,google-explicit-constructor,google-global-names-in-headers,google-readability-casting,google-runtime-int,google-runtime-operator,hicpp-*,-hicpp-vararg,misc-*,modernize-*,performance-*,readability-*,-readability-named-parameter'
CheckOptions:
    - key: bugprone-argument-comment.StrictMode
      value: 1
    - key: bugprone-exception-escape.FunctionsThatShouldNotThrow
      value: WinMain,SDL_main
    - key: misc-non-private-member-variables-in-classes.IgnoreClassesWithAllMemberVariablesBeingPublic
      value: 1
FormatStyle: 'file'
```

I think there is no `.clangd` file in my workspace.
