### ISSUE TITLE
Configure fallback compile flags for C and C++ separately

### ISSUE THREAD

**Issue by Locietta** [clangd/vscode-clangd#264]
When I have some single-file c/c++ codes, I would like them to be parsed without having to generate `compile_commands.json` . 

Normally it works fine with the clangd-vscode extension, but if I want to set some fallback flags that's specific for C++ (e.g. `-std=c++17`), the result isn't so satisfying👇

![image](https://user-images.githubusercontent.com/53137814/144752037-3ccac9f2-5f72-4f89-b025-592b9858fe13.png)

I'll be very happy to have a way to configure fallback flags separately for C and C++. (or there's already one? Please let me know!)

**Comment by HighCommander4** [comment]
If your clangd user config file (located at `~/.config/clangd/config.yaml` or similar), you can have sections of the config file that only apply to certain paths using [If blocks](https://clangd.llvm.org/config.html#if).

Here's an example of a config file fragment that applies `-std=gnu++17` to files ending in `.cpp` and `-std=gnu17` to files ending in `.c`:

```
If:
  PathMatch: .*.cpp

CompileFlags:
  Add: [-std=gnu++17]

---

If:
  PathMatch: .*.c

CompileFlags:
  Add: [-std=gnu17]
```

**Comment by Locietta** [comment]
The if blocks method works perfectly. Thanks for your time!

**Comment by chengdaweicheng** [comment]
> In your clangd user config file (located at `~/.config/clangd/config.yaml` or similar), you can have sections of the config file that only apply to certain paths using [If blocks](https://clangd.llvm.org/config.html#if).
> 
> Here's an example of a config file fragment that applies `-std=gnu++17` to files ending in `.cpp` and `-std=gnu17` to files ending in `.c`:
> 
> ```
> If:
>   PathMatch: .*\.cpp
> 
> CompileFlags:
>   Add: [-std=gnu++17]
> 
> ---
> 
> If:
>   PathMatch: .*\.c
> 
> CompileFlags:
>   Add: [-std=gnu17]
> ```

Thanks！！！sincerely！！！

**Comment by cuzperf** [comment]
> In your clangd user config file (located at `~/.config/clangd/config.yaml` or similar), you can have sections of the config file that only apply to certain paths using [If blocks](https://clangd.llvm.org/config.html#if).
> 
> Here's an example of a config file fragment that applies `-std=gnu++17` to files ending in `.cpp` and `-std=gnu17` to files ending in `.c`:
> 
> ```
> If:
>   PathMatch: .*\.cpp
> 
> CompileFlags:
>   Add: [-std=gnu++17]
> 
> ---
> 
> If:
>   PathMatch: .*\.c
> 
> CompileFlags:
>   Add: [-std=gnu17]
> ```

Thanks ! I adapt it for macos: <https://clangd.llvm.org/config#files> , edit `~/Library/Preferences/clangd/config.yaml`

``` yaml
If:
  PathMatch: [.*\.cpp, .*\.cc, .*.h]

CompileFlags:
  Add: [-std=gnu++17]

---

If:
  PathMatch: .*\.c

CompileFlags:
  Add: [-std=gnu89]
```
