### ISSUE TITLE
Disables checking of clang-tidy for files outside the current working directory

### ISSUE THREAD

**Issue by linqingyao** [clangd/vscode-clangd#431]
When I enable the **clang-tidy** check for **clangd** and set the relevant check item in the configuration file, when I jump to the standard library by clicking the link for the function, numerous suggestions appear for the set check item😣.

I would like to be able to specify that clangd only check the current working directory when using clang-tidy and not any open files.

**Comment by HighCommander4** [comment]
Maybe adding something like this to `.clangd` in your project's root directory would work:

```yaml
If:
  PathExclude: /path/to/project/.*

Diagnostics:
  ClangTidy:
    Remove: '*'
```
