### ISSUE TITLE
use gcc header search to keep compatible with gdb

### ISSUE THREAD

**Issue by czg-sci-42ver** [clangd/vscode-clangd#468]
Note: we mostly implement features in the clangd language server, and rely on Microsoft's LSP client framework to expose these in VSCode. Features requiring a lot of VSCode-specific work are unlikely to be implemented.

I faced with gdb problem to get macro debug with '-g3 -ggdb3' , so I try find header file jump in vscode but jump to clang dir.
clangd.log
```log
I[16:44:16.953] Failed to find compilation database for /home/czg/CSAPP-3e-Solutions/site/content/chapter2/code/2.89.c
I[16:44:16.953] ASTWorker building file /home/czg/CSAPP-3e-Solutions/site/content/chapter2/code/2.89.c version 1 with command clangd fallback
[/home/czg/CSAPP-3e-Solutions/site/content/chapter2/code]
/usr/bin/gcc -Wall -Wextra -Werror -Wno-parentheses -Wno-shift-count-negative -resource-dir=/usr/lib/llvm-14/lib/clang/14.0.0 -- /home/czg/CSAPP-3e-Solutions/site/content/chapter2/code/2.89.c
V[16:44:16.954] Driver produced command: cc1 -cc1 -triple x86_64-pc-linux-gnu -fsyntax-only -disable-free -clear-ast-before-backend -disable-llvm-verifier -discard-value-names -main-file-name 2.89.c -mrelocation-model pic -pic-level 2 -pic-is-pie -mframe-pointer=all -fmath-errno -ffp-contract=on -fno-rounding-math -mconstructor-aliases -funwind-tables=2 -target-cpu x86-64 -tune-cpu generic -mllvm -treat-scalable-fixed-error-as-warning -debugger-tuning=gdb -fcoverage-compilation-dir=/home/czg/CSAPP-3e-Solutions/site/content/chapter2/code -resource-dir /usr/lib/llvm-14/lib/clang/14.0.0 -internal-isystem /usr/lib/llvm-14/lib/clang/14.0.0/include -internal-isystem /usr/local/include -internal-isystem /usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../x86_64-linux-gnu/include -internal-externc-isystem /usr/include/x86_64-linux-gnu -internal-externc-isystem /include -internal-externc-isystem /usr/include -Wall -Wextra -Werror -Wno-parentheses -Wno-shift-count-negative -fdebug-compilation-dir=/home/czg/CSAPP-3e-Solutions/site/content/chapter2/code -ferror-limit 19 -fgnuc-version=4.2.1 -faddrsig -D__GCC_HAVE_DWARF2_CFI_ASM=1 -x c /home/czg/CSAPP-3e-Solutions/site/content/chapter2/code/2.89.c
```
where `-resource-dir=/usr/lib/llvm-14/lib/clang/14.0.0` always exist despite that I use `~/.config/clangd/config.yaml`
```yaml
If:                               # Apply this config conditionally
  PathMatch: .*\.c
CompileFlags:                     # Tweak the parse settings
  Compiler: /usr/bin/gcc
# https://askubuntu.com/questions/773283/how-do-i-use-c11-with-g
  Add: [-Wall,-Wextra,-Werror,-Wno-parentheses,-Wno-shift-count-negative] 
  Remove: [-I,-resource-dir=*,-internal-isystem]
```
if use 
```yaml
Compiler: clang
Add: [-Wall,-Wextra,-Werror,-Wno-parentheses,-Wno-shift-count-negative,--gcc-toolchain]
...
```
still not work.
