### ISSUE TITLE
format err with 'RawStringFormats'

### ISSUE THREAD

**Issue by USTHzhanglu** [clangd/vscode-clangd#680]
Please describe the problem.
For hints on what information is helpful, see: https://clangd.llvm.org/troubleshooting.html

If you can, provide a minimal chunk of code that shows the problem (either inline, or attach it if larger).
.clang-format
```yaml
Language:        Cpp
BasedOnStyle:  LLVM
AccessModifierOffset: -4
IndentWidth:     4
RawStringFormats:
  - Language: TextProto
      Delimiters:
        - pb
      EnclosingFunctions:
        - PARSE_TEXT_PROTO
      BasedOnStyle: google

```
**Logs**
Please attach the clangd log from the "Output" window if you can.
If possible, run with `--log=verbose` - note that the logs will include the contents of open files!
```shell

V[15:44:25.607] <<< {
  "id": 108,
  "jsonrpc": "2.0",
  "method": "textDocument/formatting",
  "params": {
    "options": {
      "insertSpaces": true,
      "tabSize": 4
    },
    "textDocument": {
      "uri": "/***/main.c"
    }
  }
}

I[15:44:25.607] <-- textDocument/formatting(108)
/***/.clang-format:124:17: error: Unexpected token. Expected Key or Block End
      Delimiters:
                ^
I[15:44:25.608] getStyle() failed for file /***/main.c: Error reading /***/.clang-format: Invalid argument. Fallback is LLVM style.
I[15:44:25.610] --> reply:textDocument/formatting(108) 3 ms
V[15:44:25.610] >>> {
  "id": 108,
  "jsonrpc": "2.0",
  "result": []
}

```
**System information**
Clangd version (from the log, or `clangd --version`):
```shell
clangd --version
clangd version 19.1.0-rc1 (https://github.com/llvm/llvm-project.git a4902a36d5c27c3a5199cd1ba91eba17910fdd68)
Features: windows
Platform: x86_64-w64-windows-gnu; target=x86_64-w64-mingw32
```
clangd extension version:
0.1.29
Operating system:
windows10 22H2
